/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 untitled.glb --transform --simplify 
Files: untitled.glb [17.37MB] > D:\ThanhVR\2.PUBLIC\1.TUAN-7\funny-thanh-portfolio-vite\public\models\untitled-transformed.glb [1.86MB] (89%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.arm_arm_mat_0.geometry} material={materials.arm_mat} scale={0.093} />
      <mesh geometry={nodes.Cables_cables_mat_0.geometry} material={materials.cables_mat} scale={0.093} />
      <mesh geometry={nodes.computer_computer_mat_0.geometry} material={materials.computer_mat} scale={0.093} />
      <mesh geometry={nodes.Ground_ground_mat_0.geometry} material={materials.ground_mat} scale={0.093} />
      <mesh geometry={nodes.keyboard_mat_mat_mat_0.geometry} material={materials.mat_mat} scale={0.093} />
      <mesh geometry={nodes.peripherals_key_mat_0.geometry} material={materials.key_mat} scale={0.093} />
      <mesh geometry={nodes.props_props_mat_0.geometry} material={materials.props_mat} scale={0.093} />
      <mesh geometry={nodes.screen_screens_0.geometry} material={materials.screens} scale={0.093} />
      <mesh geometry={nodes.screen_glass_glass_0.geometry} material={materials.glass} scale={0.093} />
      <mesh geometry={nodes.server_server_mat_0.geometry} material={materials.server_mat} scale={0.093} />
      <mesh geometry={nodes.shelf_stand_mat_0.geometry} material={materials.stand_mat} scale={0.093} />
      <mesh geometry={nodes.table_table_mat_0.geometry} material={materials.table_mat} scale={0.093} />
      <mesh geometry={nodes.Tv_tv_mat_0.geometry} material={materials.tv_mat} scale={0.093} />
      <mesh geometry={nodes.vhs_vhsPlayer_mat_0.geometry} material={materials.vhsPlayer_mat} scale={0.093} />
    </group>
  )
}

useGLTF.preload('/untitled-transformed.glb')
